version: 1

plugins:
  - name: "biome"
    enabled: true
    config:
      format: true
      lint: true

  - name: "eslint"
    enabled: true
    config:
      extensions: [".ts", ".tsx", ".js", ".jsx"]

  - name: "prettier"
    enabled: false # Using biome instead

  - name: "typescript"
    enabled: true
    config:
      strict: true

  - name: "semgrep"
    enabled: true
    config:
      rules:
        - "security"
        - "correctness"
        - "performance"

checks:
  - name: "file-size"
    enabled: true
    config:
      max_size: 1000000 # 1MB

  - name: "line-length"
    enabled: true
    config:
      max_length: 120

  - name: "complexity"
    enabled: true
    config:
      max_complexity: 15

  - name: "test-coverage"
    enabled: true
    config:
      min_coverage: 80

exclude:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".next/**"
  - "coverage/**"
  - "storybook-static/**"
  - "test-results/**"
  - "playwright-report/**"
  - "**/*.min.js"
  - "**/*.min.css"
  - "bun.lock"
  - "package-lock.json"
  - "yarn.lock"
  # Test files - exclude from code quality analysis to reduce duplication noise
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.test.js"
  - "**/*.test.jsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.spec.js"
  - "**/*.spec.jsx"
  - "tests/**"
  - "e2e/**"
  - "**/__tests__/**"
  - "**/*.stories.ts"
  - "**/*.stories.tsx"
  - "**/*.stories.js"
  - "**/*.stories.jsx"

targets:
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.json"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
