[test]
# Bun test configuration for utility/logic tests only
coverage = true
timeout = 10000
bail = 1
verbose = true
environment = "happy-dom"
setup = ["./bun-test-setup.ts"]

# Coverage configuration for logic tests
coverage_dir = "./coverage/bun-logic"
coverage_threshold = 85
coverage_exclude = [
  "node_modules/**",
  "dist/**",
  ".next/**",
  "coverage/**",
  "tests/**",
  "**/*.d.ts",
  "**/*.config.{js,ts}",
  "**/*.stories.{js,ts,jsx,tsx}",
  "**/types.ts",
  "**/.storybook/**",
  "**/storybook-static/**",
  "scripts/**",
  "docs/**",
  "public/**",
  "playwright-report/**",
  "test-results/**",
  "components/**",
  "app/**/*.{jsx,tsx}",
  "src/components/**",
  "hooks/**/*.{jsx,tsx}"
]
coverage_reporter = ["lcov", "text", "html", "json"]

# Test file patterns - ONLY specific utility/logic tests that we've fixed for Bun
include = [
  "lib/telemetry.test.ts",
  "lib/stream-utils.test.ts",
  "lib/github-api.test.ts",
  "lib/auth/index.test.ts",
  "lib/message-handlers.test.ts",
  "lib/auth.test.ts",
  "lib/container-types.test.ts",
  "lib/utils.test.ts",
  "lib/inngest.test.ts",
  "lib/inngest-isolated.test.ts",
  "lib/inngest-standalone.test.ts",
  "lib/inngest.unit.test.ts"
]

# Explicitly exclude ALL files that use vi.mock or are React/integration tests
exclude = [
  # ALL React component tests (handled by Vitest)
  "**/*.test.{jsx,tsx}",
  "components/**/*.test.{js,jsx,ts,tsx}",
  "app/**/*.test.{js,jsx,ts,tsx}",
  "hooks/**/*.test.{js,jsx,ts,tsx}",
  "src/components/**/*.test.{js,jsx,ts,tsx}",

  # Integration and E2E tests
  "tests/**",
  "**/*.integration.test.{js,jsx,ts,tsx}",
  "**/*.e2e.test.{js,jsx,ts,tsx}",

  # Files that use vi.mock (must be run with Vitest)
  "lib/auth/openai-codex.test.ts",
  "lib/auth/anthropic.test.ts",
  "lib/github.test.ts",
  "lib/inngest.test.ts",
  "src/lib/auth/pkce.test.ts",
  "src/lib/auth/claude-auth.test.ts",
  "app/actions/**/*.test.ts",
  "stores/**/*.test.ts",
  "lib/redis/**/*.test.ts",
  "lib/cache/**/*.test.ts",
  "lib/ai/**/*.test.ts",

  # Build and config files
  "node_modules/**",
  "dist/**",
  ".next/**",
  "coverage/**",
  "**/*.stories.{js,jsx,ts,tsx}",
  "**/*.config.{js,ts}"
]

# Override Bun's default test patterns to prevent auto-discovery
[test.patterns]
include = [
  "lib/telemetry.test.ts",
  "lib/stream-utils.test.ts",
  "lib/github-api.test.ts",
  "lib/auth/index.test.ts",
  "lib/message-handlers.test.ts",
  "lib/auth.test.ts",
  "lib/container-types.test.ts",
  "lib/utils.test.ts",
  "lib/inngest.test.ts",
  "lib/inngest-isolated.test.ts",
  "lib/inngest-standalone.test.ts",
  "lib/inngest.unit.test.ts"
]

# Mock configuration
mock = true
mockReset = true

# Path alias configuration for Bun tests
[test.alias]
"@" = "./"
"@/app" = "./app"
"@/components" = "./components"
"@/lib" = "./lib"
"@/hooks" = "./hooks"
"@/stores" = "./stores"
"@/types" = "./types"
"@/features" = "./src/features"
"@/shared" = "./src/shared"
"@/test" = "./tests"
"@/src" = "./src"

# Coverage reporting specifically for logic tests
coverage_include = [
  "lib/**/*.{js,ts}",
  "src/lib/**/*.{js,ts}",
  "src/schemas/**/*.{js,ts}",
  "stores/**/*.{js,ts}",
  "src/hooks/useZodForm/**/*.{js,ts}",
  "src/shared/**/*.{js,ts}",
  "src/types/**/*.{js,ts}"
]