[test]
# Bun test configuration for utility/logic tests only
coverage = true
timeout = 10000
bail = 1
verbose = true
environment = "happy-dom"
setup = ["./bun-test-setup.ts"]
# Disable auto-discovery to prevent React component tests from being included
auto_discover = false

# Coverage configuration for logic tests
coverage_dir = "./coverage/bun-logic"
coverage_threshold = 85
coverage_exclude = [
  "node_modules/**",
  "dist/**",
  ".next/**",
  "coverage/**",
  "tests/**",
  "**/*.d.ts",
  "**/*.config.{js,ts}",
  "**/*.stories.{js,ts,jsx,tsx}",
  "**/types.ts",
  "**/.storybook/**",
  "**/storybook-static/**",
  "scripts/**",
  "docs/**",
  "public/**",
  "playwright-report/**",
  "test-results/**",
  "components/**",
  "app/**/*.{jsx,tsx}",
  "src/components/**",
  "hooks/**/*.{jsx,tsx}"
]
coverage_reporter = ["lcov", "text", "html", "json"]

# Test file patterns - ONLY specific utility/logic tests (no React components)
# Using explicit file paths to prevent any React component tests from being included
include = [
  "test-minimal.test.ts",
  "lib/telemetry.test.ts",
  "lib/stream-utils.test.ts",
  "lib/github-api.test.ts",
  "lib/auth.test.ts",
  "lib/utils.test.ts",
  "lib/container-types.test.ts",
  "src/lib/auth/pkce.test.ts",
  "src/schemas/**/*.test.ts",
  "src/hooks/useZodForm/**/*.test.ts",
  "src/shared/schemas/**/*.test.ts"
]

# Explicitly exclude ALL React component tests and integration tests
exclude = [
  # ALL React component tests (handled by Vitest)
  "**/*.test.{jsx,tsx}",
  "components/**/*.test.{js,jsx,ts,tsx}",
  "app/**/*.test.{js,jsx,ts,tsx}",
  "hooks/**/*.test.{js,jsx,ts,tsx}",
  "src/components/**/*.test.{js,jsx,ts,tsx}",

  # Integration and E2E tests
  "tests/**",
  "**/*.integration.test.{js,jsx,ts,tsx}",
  "**/*.e2e.test.{js,jsx,ts,tsx}",

  # Specific problematic files that contain React/JSX
  "lib/auth/openai-codex.test.ts",
  "lib/github.test.ts",
  "lib/inngest.test.ts",
  "app/actions/**/*.test.ts",
  "stores/**/*.test.ts",

  # Build and config files
  "node_modules/**",
  "dist/**",
  ".next/**",
  "coverage/**",
  "**/*.stories.{js,jsx,ts,tsx}",
  "**/*.config.{js,ts}"
]

# Override Bun's default test patterns to prevent auto-discovery
[test.patterns]
include = [
  "test-minimal.test.ts",
  "lib/telemetry.test.ts",
  "lib/stream-utils.test.ts",
  "lib/github-api.test.ts",
  "lib/auth.test.ts",
  "lib/utils.test.ts",
  "lib/container-types.test.ts",
  "src/lib/auth/pkce.test.ts",
  "src/schemas/**/*.test.ts",
  "src/hooks/useZodForm/**/*.test.ts",
  "src/shared/schemas/**/*.test.ts"
]
exclude = [
  "**/*.test.{jsx,tsx}",
  "components/**",
  "app/**",
  "hooks/**",
  "src/components/**",
  "tests/**"
]

# Mock configuration
mock = true
mockReset = true

# Coverage reporting specifically for logic tests
coverage_include = [
  "lib/**/*.{js,ts}",
  "src/lib/**/*.{js,ts}",
  "src/schemas/**/*.{js,ts}",
  "stores/**/*.{js,ts}",
  "src/hooks/useZodForm/**/*.{js,ts}",
  "src/shared/**/*.{js,ts}",
  "src/types/**/*.{js,ts}"
]