// Quick JWT decoder to extract Vercel information
const token =
  'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1yay00MzAyZWMxYjY3MGY0OGE5OGFkNjFkYWRlNGEyM2JlNyJ9.eyJpc3MiOiJodHRwczovL29pZGMudmVyY2VsLmNvbS9yeWFuLWxpc3Nlcy1wcm9qZWN0cyIsInN1YiI6Im93bmVyOnJ5YW4tbGlzc2VzLXByb2plY3RzOnByb2plY3Q6dmliZXgtYXBwOmVudmlyb25tZW50OmRldmVsb3BtZW50Iiwic2NvcGUiOiJvd25lcjpyeWFuLWxpc3Nlcy1wcm9qZWN0czpwcm9qZWN0OnZpYmV4LWFwcDplbnZpcm9ubWVudDpkZXZlbG9wbWVudCIsImF1ZCI6Imh0dHBzOi8vdmVyY2VsLmNvbS9yeWFuLWxpc3Nlcy1wcm9qZWN0cyIsIm93bmVyIjoicnlhbi1saXNzZXMtcHJvamVjdHMiLCJvd25lcl9pZCI6InRlYW1fb3VxWUg3Y0YyVWZWV042ZERocnlNU0VNIiwicHJvamVjdCI6InZpYmV4LWFwcCIsInByb2plY3RfaWQiOiJwcmpfOWZwUHBYTmptbXpOOHZsaWdLYkFmTEpXM3ZXdyIsImVudmlyb25tZW50IjoiZGV2ZWxvcG1lbnQiLCJ1c2VyX2lkIjoicWhqelRZRWtWbldFSzk2NUpMeFR4NlFjIiwibmJmIjoxNzUyOTM4NDA1LCJpYXQiOjE3NTI5Mzg0MDUsImV4cCI6MTc1Mjk4MTYwNX0.CFwONg87BnT7bgV-oNP2uJZQ4iwovw92w3FDmt_xfcoZzYHm_GcfLyJwsasBHKCuh4em6ShYQOTMM-kKDJq_Qj_1eD9Nq3L2MLnqEouxYCVZdgXzYCWfG1ZKYYjiVHkAICGpyu6_3bTgJCyT2qSALkAXuYlt8MDgUaTd-aMwJGRL6N4w3uQqFFrwYuHOVnatbDr2ii83FkhH9RUjqacNX8Fi7BncEmQXl8cAqiNibiGpbFun1s5OD6RxAewNrQiLeAM2W9gjmMSRQJ7wzK6RMmYCdkHMM9d9-rBope4inCIEs9luCdEheidFK9OCj8J5ZorcYUoElzPYFKWko-9UZw'

// Split the JWT into its three parts
const parts = token.split('.')
const payload = parts[1]

// Decode the base64 payload
const decodedPayload = JSON.parse(atob(payload))

console.log('🔍 Decoded JWT Payload:')
console.log(JSON.stringify(decodedPayload, null, 2))

console.log('\n📋 Extracted Vercel Information:')
console.log(`VERCEL_ORG_ID: ${decodedPayload.owner_id}`)
console.log(`VERCEL_PROJECT_ID: ${decodedPayload.project_id}`)
console.log(`Project Name: ${decodedPayload.project}`)
console.log(`Owner: ${decodedPayload.owner}`)
