import path from 'node:path'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'
import { defineConfig } from 'vitest/config'

// Component tests config for React components and hooks
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './'),
      '@/components': path.resolve(__dirname, './components'),
      '@/lib': path.resolve(__dirname, './lib'),
      '@/hooks': path.resolve(__dirname, './hooks'),
      '@/app': path.resolve(__dirname, './app'),
      '@/features': path.resolve(__dirname, './src/features'),
      '@/shared': path.resolve(__dirname, './src/shared'),
      '@/test': path.resolve(__dirname, './tests'),
      '@/fixtures': path.resolve(__dirname, './tests/fixtures'),
      '@/mocks': path.resolve(__dirname, './tests/mocks'),
      '@/db': path.resolve(__dirname, './db'),
      '@/stores': path.resolve(__dirname, './stores'),
      '@/src': path.resolve(__dirname, './src'),
    },
  },
  optimizeDeps: {
    include: [
      '@testing-library/react',
      '@testing-library/jest-dom',
      '@testing-library/user-event',
      'react',
      'react-dom',
      'react/jsx-runtime',
    ],
    exclude: ['fsevents', 'playwright', 'playwright-core', 'chromium-bidi'],
  },
  build: {
    rollupOptions: {
      external: ['fsevents', 'playwright', 'playwright-core', 'chromium-bidi'],
    },
  },
  esbuild: {
    target: 'es2022',
    format: 'esm',
    jsx: 'automatic',
  },
  test: {
    name: 'components',
    environment: 'jsdom',
    setupFiles: ['./tests/setup/components.ts'],
    globals: true,
    restoreMocks: true,
    clearMocks: true,
    mockReset: true,
    passWithNoTests: true,
    logHeapUsage: true,
    css: true,
    pool: 'threads',
    poolOptions: {
      threads: {
        singleThread: false,
        isolate: true,
      },
    },
    include: [
      'components/**/*.test.{jsx,tsx}',
      'app/**/*.test.{jsx,tsx}',
      'hooks/**/*.test.{jsx,tsx}',
      'src/components/**/*.test.{jsx,tsx}',
      'src/hooks/**/*.test.{jsx,tsx}',
    ],
    exclude: [
      'node_modules',
      'dist',
      '.next',
      '**/*.integration.test.*',
      '**/*.e2e.test.*',
      '**/*.browser.test.*',
      '**/*.bun.test.*',
      'tests/bun-*.test.*',
      'lib/**/*.test.*',
      'src/lib/**/*.test.*',
      'stores/**/*.test.*',
      'src/schemas/**/*.test.*',
      'src/hooks/useZodForm/**/*.test.{js,ts}',
      'app/api/**/*.test.*',
      'tests/integration/**',
      'tests/e2e/**',
      'tests/browser/**',
    ],
    testTimeout: 15_000,
    hookTimeout: 10_000,
    teardownTimeout: 10_000,
    bail: 0,
    retry: process.env.CI ? 2 : 0,
    reporters: process.env.CI ? ['verbose', 'json'] : ['verbose'],
    outputFile: process.env.CI ? './test-results/components-results.json' : undefined,
    allowOnly: false,
    coverage: {
      enabled: true,
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      reportsDirectory: './coverage/components',
      exclude: [
        'node_modules/**',
        'dist/**',
        '.next/**',
        'coverage/**',
        'tests/**',
        '**/*.d.ts',
        '**/*.config.*',
        'scripts/**',
        'lib/**',
        'src/lib/**',
        'stores/**',
      ],
    },
  },
})
