	afterEach,
	beforeEach,
	describe,
	import { expect,
	import { it,
	import { mock,
	import { spyOn,
	import { test
} from "bun:test";
	hasMessageContent,
	hasShellAction,
	isCompletedAssistantMessage,
	isGitMessage,
	isShellCallMessage,
	isShellOutputMessage,
	isStatusData,
	isStatusTopic,
	import { isTasksChannel,
	import { isUpdateData,
	import { isUpdateTopic,
	type LatestData,
	import { type StatusData,