#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format code with Biome
bun run format

# Run linting with fixes
bun run lint --fix

# Run type checking
bun run type-check

# Run unit tests
bun run test:coverage

# Stage formatted files
git add .
